### ISSUE TITLE
Las imágenes no se posicionan correctamente en el pdf autogenerado

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#1]

**Comment by arroyofe** [comment]
Bug corregido, el pdf ya permite ver correctamente las imágenes en la posición adecuada

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/1?planning-poker) with Zenhub @pac1006
