### ISSUE TITLE
Manual de usuario

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#20]
- Requisitos de la app
- Instalación

**Comment by arroyofe** [comment]
Manual de usuario disponible en la wiki local.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/20?planning-poker) with Zenhub @pac1006
