### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#21]

**Comment by arroyofe** [comment]
Publicación subida a Google Play. Aceptada por Google. utilizable desde hoy.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/21?planning-poker) with Zenhub @pac1006
