### ISSUE TITLE
Valores de los ejes incorrectos en los gráficos del tiempo

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#24]
Las leyendas no se corresponden con los valores reales en los gráficos de temperatura, lluvia y viento en la vista grabación.

**Comment by arroyofe** [comment]
Los valores entre los ejes de coordenadas esstaban invertidos. Se ha corregido el error.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/24?planning-poker) with Zenhub @pac1006
