### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#25]
[https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb](url)

**Comment by arroyofe** [comment]
Fuente del error detectada y corregida.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/25?planning-poker) with Zenhub @pac1006
