### ISSUE TITLE
Solapamiento con nombres largos en pantallas < 720px

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#26]
- Pantallas de < 720px
- Tamaño de fuente > M

**Comment by arroyofe** [comment]
Tras la modificación del programa si los nombres sobrepasan la longitud de la pantalla se añaden tantas líneas complementarias como sea requerido para que no haya solapamiento. Puede pasar a producción

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/26?planning-poker) with Zenhub @pac1006
