### ISSUE TITLE
Pasar memoria doc a latex

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#27]
- Revisar imágenes.
- Revisar bibliografía.
- bibentry ([http://gking.harvard.edu/files/bibentry2.pdf](url)).

**Documentación**

  

- [ ] Resumen
- [ ]   Introducción
- [ ]   Objetivos del proyecto
- [ ]   Conceptos teóricos
- [ ]   Técnicas y herramientas
- [ ]   Aspectos relevantes
- [ ]   Trabajos relacionados
- [ ]   Conclusiones y Líneas de trabajo futuras

**Comment by arroyofe** [comment]
Documentación terminada.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/27?planning-poker) with Zenhub @pac1006
