### ISSUE TITLE
Gráfico incorrecto con grabación a 0

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#28]
Cuando todos los registros de la grabación están a 0 el gráfico no se construye correctamente.![46fc1660-e497-11e6-8099-496fe0ee310f.jpeg](https://images.zenhubusercontent.com/63773dbff2a19e5b22450d0a/7e422fcb-62d0-4ff0-8eb2-72864473c10c)

**Comment by arroyofe** [comment]
Bug resuelto con una nueva programación.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/28?planning-poker) with Zenhub @pac1006
