### ISSUE TITLE
Pasar anexos a latex

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#29]
**Anexos**

- [ ]   Plan del proyecto software
- [ ]   Especificación de Requisitos
- [ ]   Especificación de diseño
- [ ]   Manual del programador
- [ ]   Manual de usuario

Expresión regular para corregir las referencias:

- Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
- Reemplazar por: \\citep{\2}

Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

- Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
- Reemplazar por: \\imagen{\2}{descripción...}

Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by arroyofe** [comment]
Hecho.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/29?planning-poker) with Zenhub @pac1006
