### ISSUE TITLE
Pasar SonarQube tribunal

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#31]
![Captura de pantalla 2022-11-18 a las 17.04.22.png](https://images.zenhubusercontent.com/63773dbff2a19e5b22450d0a/5a2a0b09-1e8c-406c-9dec-41d05654136c)

**Comment by arroyofe** [comment]
Tests termiandos con éxito.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/31?planning-poker) with Zenhub @pac1006
