### ISSUE TITLE
Imprimir memoria

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#32]
La memoria ha de estar encuadernada en formato:

- Libro cosido,
- Libro pegado,
- Libro con grapa de canto metálico prensada.
- Revista de tapa dura y grapa.

No se deben usar formatos de encuadernación de tornillos, espirales, canutillos y similares.

**Comment by arroyofe** [comment]
Realizada impresión en 5 ejemplares.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/32?planning-poker) with Zenhub @pac1006
