### ISSUE TITLE
Rematar memoria

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#33]
- [ ]  Enlace Google Play.
- [ ]   Imagen CI
- [ ]   Tabla de estadísticas
- [ ]   Firmar electrónicamente
- [ ]   Imagen página web o google play

**Comment by arroyofe** [comment]
Hecho

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/33?planning-poker) with Zenhub @pac1006
