### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#42]
[https://startbootstrap.com/template-overviews/new-age/(url)
[http://www.grabon.in/mobile-apps/(url)

[http://bronto.github.io/javasphinx/(url)

**Comment by arroyofe** [comment]
Página Web creada

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/42?planning-poker) with Zenhub @pac1006
