### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#45]
- Código fuente app
- Ejecutable app
- Herramientas
- Plataforma de desarrollo del algoritmo
- Herramienta de conteo de abejas
- Documentación
- Memoria
- Anexos
- JavaDoc
- Dataset de videos

**README**

- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by arroyofe** [comment]
Todos los discos grabados

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/45?planning-poker) with Zenhub @pac1006
