### ISSUE TITLE
Diseño del aparato: estación meteorológica miniatura.

### ISSUE THREAD

**Issue by arroyofe** [pac1006/GESPRO_GESTIONTAREAS#49]

**Comment by pac1006** [comment]
Estoy contactando con varias empresas para ello

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/49?planning-poker) with Zenhub @pac1006
