### ISSUE TITLE
Diseño arquitectónico

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#5]

**Comment by arroyofe** [comment]
Diseño terminado por el arquitecto de sistemas. Disponible en la intranet.

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/5?planning-poker) with Zenhub @pac1006
