### ISSUE TITLE
Contactar mayoristas para venta del nuevo producto.

### ISSUE THREAD

**Issue by arroyofe** [pac1006/GESPRO_GESTIONTAREAS#57]

**Comment by arroyofe** [comment]
Los mayoristas habituales son reticentes con el nuevo producto. Enviarles la documentación completa.

**Comment by pac1006** [comment]
contacto realizado

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/57?planning-poker) with Zenhub @pac1006
