### ISSUE TITLE
Solapamiento con condiciones meteorológicas largas

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONTAREAS#7]

**Comment by arroyofe** [comment]
El solapamiento se permite después de la modificación del progama

**Comment by arroyofe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Practica-637763271f86512c87365d6f/issues/pac1006/GESPRO_GESTIONTAREAS/7?planning-poker) with Zenhub @pac1006
